DROP SEQUENCE M_ADDRBOOK_SEQ;
CREATE SEQUENCE M_ADDRBOOK_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE 999999 NOCYCLE NOCACHE;
DROP SEQUENCE M_ORDER_SEQ;
CREATE SEQUENCE M_ORDER_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE 999999 NOCYCLE NOCACHE;
DROP SEQUENCE M_ORDERPROD_SEQ;
CREATE SEQUENCE M_ORDERPROD_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE 999999 NOCYCLE NOCACHE;


DROP TABLE M_EVENT;
DROP TABLE M_ANSWER;
DROP TABLE M_ASK;
DROP TABLE M_CUSTOMER_COUPON;
DROP TABLE M_COUPON;
DROP TABLE M_REVIEW;
DROP TABLE M_DELIVERY;
DROP TABLE M_ORDERPROD;
DROP TABLE M_ORDER;
DROP TABLE M_PACKAGE;
DROP TABLE M_PRODUCT;
DROP TABLE M_ADDRBOOK;
DROP TABLE M_CUSTOMER;
DROP TABLE M_SEASONTONE;

CREATE TABLE M_SEASONTONE (
	M_SEASONTONE_CATEGORY VARCHAR2(30) PRIMARY KEY,
	M_SEASONTONE_COLOR1 VARCHAR2(20),
 	M_SEASONTONE_COLOR2 VARCHAR2(20),
 	M_SEASONTONE_COLOR3 VARCHAR2(20)
);

CREATE TABLE M_CUSTOMER (
	M_CUSTOMER_ID VARCHAR2(20) PRIMARY KEY,
 	M_SEASONTONE_CATEGORY VARCHAR2(30) REFERENCES M_SEASONTONE(M_SEASONTONE_CATEGORY),
	M_CUSTOMER_PW VARCHAR2(20) NOT NULL,
	M_CUSTOMER_NAME VARCHAR2(20) NOT NULL,
	M_CUSTOMER_PHONENUM CHAR(13) UNIQUE NOT NULL,
	M_CUSTOMER_BIRTH DATE NOT NULL,
	M_CUSTOMER_EMAIL VARCHAR2(50) UNIQUE NOT NULL,
	M_CUSTOMER_ADDR VARCHAR2(100) NOT NULL,
	M_CUSTOMER_JOINDATE DATE NOT NULL,
	M_CUSTOMER_POINT NUMBER,
	M_CUSTOMER_GRADE VARCHAR2(10),
	M_CUSTOMER_SUMPRICE NUMBER,
	M_CUSTOMER_AGREE CHAR(1) NOT NULL
);

CREATE TABLE M_ADDRBOOK (
	M_ADDRBOOK_NO NUMBER PRIMARY KEY,
	M_ADDRBOOK_NAME VARCHAR2(20) NOT NULL,
	M_ADDRBOOK_PHONENUM CHAR(13) NOT NULL,
	M_ADDRBOOK_ADDR VARCHAR2(100) NOT NULL,
	M_CUSTOMER_ID VARCHAR2(20) REFERENCES M_CUSTOMER(M_CUSTOMER_ID)
);

CREATE TABLE M_PRODUCT (
 	M_PRODUCT_CODE VARCHAR2(20) PRIMARY KEY,
 	M_SEASONTONE_CATEGORY VARCHAR2(30) REFERENCES M_SEASONTONE(M_SEASONTONE_CATEGORY),
 	M_PRODUCT_CATEGORY NUMBER NOT NULL,
 	M_PRODUCT_NAME VARCHAR2(30) NOT NULL,
 	M_PRODUCT_COLOR VARCHAR2(10) NULL,
 	M_PRODUCT_PRICE NUMBER NULL,
 	M_PRODUCT_DISCOUNT NUMBER NULL,
 	M_PRODUCT_INVENTORY NUMBER NULL,
 	M_PRODUCT_REGDATE DATE NOT NULL,
 	M_PRODUCT_IMAGE VARCHAR2(100) NULL
);

CREATE TABLE M_PACKAGE (
 	M_PACKAGE_NO NUMBER PRIMARY KEY,
 	M_PRODUCT_CODE VARCHAR2(20) REFERENCES M_PRODUCT(M_PRODUCT_CODE),
 	M_SEASONTONE_CATEGORY VARCHAR2(30) REFERENCES M_SEASONTONE(M_SEASONTONE_CATEGORY),
 	M_PRODUCT_CODE2 VARCHAR2(20) NULL,
 	M_PRODUCT_CODE3 VARCHAR2(20) NULL,
 	M_PRODUCT_CODE4 VARCHAR2(20) NULL,
 	M_PACKAGE_IMAGE VARCHAR2(20) NULL,
 	M_PACKAGE_PRICE NUMBER NULL,
 	M_PACKAGE_DISCOUNT NUMBER NULL
);

CREATE TABLE M_ORDER (
 	M_ORDER_NO VARCHAR2(20) PRIMARY KEY,
 	M_CUSTOMER_ID VARCHAR2(20) REFERENCES M_CUSTOMER(M_CUSTOMER_ID),
 	M_ORDER_NAME VARCHAR2(20) NULL,
 	M_ORDER_PHONENUM CHAR(13) NOT NULL,
 	M_ORDER_ADDR VARCHAR2(100) NOT NULL,
 	M_ORDER_PAYMENT VARCHAR2(10) NULL,
 	M_ORDER_DATE DATE NULL,
 	M_ORDER_TOTALPRICE NUMBER NULL,
 	M_ORDER_DEPOSITPRICE NUMBER NULL
);

CREATE TABLE M_ORDERPROD (
 	M_ORDERPROD_NO NUMBER PRIMARY KEY,
 	M_ORDER_NO VARCHAR2(20) REFERENCES M_ORDER(M_ORDER_NO),
 	M_PRODUCT_CODE VARCHAR2(20) REFERENCES M_PRODUCT(M_PRODUCT_CODE),
 	M_CUSTOMER_ID VARCHAR2(20) REFERENCES M_CUSTOMER(M_CUSTOMER_ID),
 	M_ORDERPROD_COUNT NUMBER NULL,
 	M_ORDERPROD_PRICE NUMBER NULL,
 	M_ORDERPROD_CHECK CHAR(1) NOT NULL,
 	M_ORDERPROD_REVIEWCHECK CHAR(1) NOT NULL
);

CREATE TABLE M_DELIVERY (
 	M_OPRDER_NO VARCHAR2(20) PRIMARY KEY,
 	M_DELIVERY_STATUS VARCHAR2(10) NOT NULL,
 	M_DELIVERY_COMPANY VARCHAR2(20) NOT NULL,
 	M_DELIVERY_STARTDATE DATE NOT NULL,
 	M_DELIVERY_ENDDATE DATE NULL,
 	M_DELIVERY_NO VARCHAR2(20) NULL
);

CREATE TABLE M_REVIEW (
 	M_REVIEW_NO NUMBER PRIMARY KEY,
 	M_CUSTOMER_ID VARCHAR2(20) REFERENCES M_CUSTOMER(M_CUSTOMER_ID),
 	M_PRODUCT_CODE VARCHAR2(20) REFERENCES M_PRODUCT(M_PRODUCT_CODE),
 	M_REVIEW_CONTENT VARCHAR2(2000) NOT NULL,
 	M_REVIEW_IMAGE1 VARCHAR2(100) NULL,
 	M_REVIEW_IMAGE2 VARCHAR2(100) NULL,
 	M_REVIEW_STAR NUMBER NOT NULL
);

CREATE TABLE M_COUPON (
 	M_COUPON_NO NUMBER PRIMARY KEY,
 	M_PRODUCT_CODE VARCHAR2(20) REFERENCES M_PRODUCT(M_PRODUCT_CODE),
 	M_COUPON_COUNT NUMBER NULL,
 	M_COUPON_DISCOUNT NUMBER NOT NULL,
 	M_COUPON_CATEGORY NUMBER NULL,
 	M_COUPON_ENDDATE DATE NULL
);

CREATE TABLE M_CUSTOMER_COUPON (
 	M_NO NUMBER PRIMARY KEY,
 	M_CUSTOMER_ID VARCHAR2(20) REFERENCES M_CUSTOMER(M_CUSTOMER_ID),
 	M_COUPON_NO NUMBER REFERENCES M_COUPON(M_COUPON_NO)
);

CREATE TABLE M_ASK (
 	M_ASK_NO NUMBER PRIMARY KEY,
 	M_CUSTOMER_ID VARCHAR2(20) REFERENCES M_CUSTOMER(M_CUSTOMER_ID),
 	M_PRODUCT_CODE VARCHAR2(20) REFERENCES M_PRODUCT(M_PRODUCT_CODE),
 	M_ASK_CATEGORY VARCHAR2(20) NOT NULL,
 	M_ASK_TITLE VARCHAR2(100) NOT NULL,
 	M_ASK_CONTENT VARCHAR(4000) NOT NULL,
 	M_ASK_DATE DATE NOT NULL,
 	M_ASK_PW VARCHAR2(20) NULL,
 	M_ASK_PWCHECK CHAR(1) NOT NULL,
 	M_ASK_IMAGE1 VARCHAR2(100) NULL,
 	M_ASK_IMAGE2 VARCHAR2(100) NULL,
 	M_ASK_ANSWERDONE CHAR(1) NOT NULL
);

CREATE TABLE M_ANSWER (
 	M_ANSWER_NO NUMBER PRIMARY KEY,
 	M_ASK_NO NUMBER REFERENCES M_ASK(M_ASK_NO),
 	M_ANSWER_DATE DATE NOT NULL,
 	M_ANSWER_CONTENT VARCHAR(4000) NOT NULL
);

CREATE TABLE M_EVENT (
 	M_EVENT_NO NUMBER PRIMARY KEY,
 	M_EVENT_TITLE VARCHAR2(100) NOT NULL,
 	M_EVENT_CONTENT VARCHAR2(4000) NULL,
 	M_EVENT_IMAGE VARCHAR2(100) NULL,
 	M_EVENT_STARTDATE DATE NULL,
 	M_EVENT_ENDDATE DATE NULL
);